services:
  backend:
    user: nobody
    build:
      context: ./backend
    command: ["./stargazer"]
    ports:
      - "3000:3000"

  frontend:
    user: node
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host=0.0.0.0", "--port=3001"]
    ports:
      - "3001:3001"

  postgres:
    image: postgres:18
    volumes:
      - postgres-volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=stargazer
    ports:
      - "5432:5432"
    restart: always

volumes:
  frontend-node-modules:
  postgres-volume:
